### ISSUE TITLE
SetWallpaper failed

### ISSUE THREAD

**Issue by achimfrase** [flathub/im.bernard.Nostalgia#13]
I get an error when I try to set an wallpaper.

flatpak run im.bernard.Nostalgia 

(nostalgia:2): GLib-CRITICAL **: 13:37:57.703: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(nostalgia:2): GLib-CRITICAL **: 13:37:57.716: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(nostalgia:2): GLib-CRITICAL **: 13:37:57.733: g_hash_table_lookup: assertion 'hash_table != NULL' failed
** Message: 13:38:00.714: window.vala:133: Saving day.jpg as /var/home/achimfrase/.var/app/im.bernard.Nostalgia/data/day.jpg
** Message: 13:38:00.764: window.vala:133: Saving morning.jpg as /var/home/achimfrase/.var/app/im.bernard.Nostalgia/data/morning.jpg
** Message: 13:38:00.771: window.vala:133: Saving night.jpg as /var/home/achimfrase/.var/app/im.bernard.Nostalgia/data/night.jpg

** (nostalgia:2): CRITICAL **: 13:38:00.784: window.vala:96: SetWallpaper failed

System Information:
Flatpak 1.12.4

$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="35.20220129.0 (Silverblue)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35.20220129.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='35.20220129.0'

Maybe you have an Idea what's wrong.

Regards, Achim

**Comment by bertob** [comment]
Could you please file bugs against the app repo (https://gitlab.gnome.org/bertob/nostalgia/)? This is just for packaging :)

**Comment by achimfrase** [comment]
Okay, thanks for the hint. -> [https://gitlab.gnome.org/bertob/nostalgia/-/issues/15](url) done.
