### ISSUE TITLE
Missing D-bus session permission in flatpak sandbox to set wallpaper

### ISSUE THREAD

**Issue by antwnymos** [flathub/im.bernard.Nostalgia#9]
Right after it is installed, the app doesn't set the wallpaper when clicking on one, however after configuring the flatpak sandbox to allow access to the D-bus session bus (socket=session-bus, I used flatseal cuz it's easier) I successfully see a prompt from GNOME to allow the app to set the wallpaper or not and pressing yes grants the permission. Also looking at the perms in flatseal there are no allowed names on the session bus, I suppose one could be easily added.

**Comment by alice-mkh** [comment]
The app is using the wallpaper portal. It doesn't require permissions, they are implicit.
